### PR TITLE
feature/social-share

### LINKED ISSUE #25: Component: Social Share
Display the social media share icons for a post

- [x] Facebook
- [x] Twitter
- [x] LinkedIn
- [x] Email
- [x] Copy Link

### PR DESCRIPTION
**Pull request by aleesteele**
closes #25 
- Social share component that appears at large breakpoint
- Used tippy to make tooltip that appears when link has been copied

### CODE REVIEW

**Comment by leezaweb** [comment]
@aleesteele This is really coming along. Great use of rel and aria labels and your javascript is excellent. A few edits:
**Javascript**
- The "Copied!" popup only appears on the second click. Tippy needs to be initiated outside of the clipboard's success event. If you truly only want the popup to show not on a 'click' event but only on the clipboard's success event, you should set the trigger to manual and trigger the popup within that success callback. You'll have to figure out how to manually trigger the correct popup.
- You should add padding to that popup. You can do it inline in the js. Example:  `content: '<span style="padding: __px">Copied!</span>'`
- Don't forget to delete that console.log

**Styles**
- The flex properties should be applied to the ul, but they are being applied to the div. Same goes for that bottom border and bottom padding. Then [delete "display:inline-block on line 63](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L63) and then delete lines 15,16, and 17

- Add "list-style-type: none" to the ul at line 9

- [Make line 64 margin-right instead of padding-right](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L64). And you don't need to[ justify with space-between](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L10) in the header and you're overwriting that in the footer

- [Delete line 32](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L32) since you don't need to float something that's absolute positioned

- You don't need [line 51 ("flex-direction: row")](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L51)

- [Delete line 59](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L59). "left" is not a possible value for the property align-items and it's not needed anyway.

-  You should [make the line height header component 2 instead of 1.5](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L36)

- How did you determine that the hover state should be [$color__blue-dark?](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L43). I can't find hover states for the header or footer icons anywhere in Zeplin would think these top icons should be $color__astral. And there's a possibility the bottom icons should be $color__orange-dark
---

@jnschrag Can the social.html include from the Jekyll Starter Kit now be deleted? And I think [line 158 of _post.scss](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/pages/_post.scss#L158) should be adjusted

**Comment by aleesteele** [comment]
Thank you so much, @leezaweb for these thorough comments! Addressed these in order:
- [ ] Manually triggers tooltip w/ click
- [ ] Added padding to the tooltip
- [ ] Deleted console.log (woops)
- [ ] Applied flex properties, border bottom, 100% width, and padding to ul in the footer. Deleted , applied border bottom to <ul>
- [ ] Applied flex properties to ul insteadThe flex properties should be applied to the ul, but they are being applied to the div. Same goes for that bottom border and bottom padding. Then [delete "display:inline-block on line 63](https://github.com/CSIS-iLab/on-the-radar/blob/36802406c77feec4c4b206b50215c211a25d1094/assets/_sass/components/_social-share.scss#L63) and then delete lines 15, 16, and 17
- [ ] added "list-style-type: none" to the global ul 
- [ ] changed padding-right to margin-right. deleted space-between in the header
- [ ] deleted float property, align-items, and flex-direction
- [ ] changed line-height in the header to 2
- [ ] To be honest, I don't remember. I might have asked about it in person. In any case, changed those hover styles to `$color__astral` and `$color__orange-dark` in the header and footer, respectively

**Comment by aleesteele** [comment]
As we just talked about this mornin':
* added position relative to the post-meta element. I can't check to see if this fixes the problems on larger screens, but please let me know if you notice anything...
* fixed the javascript so that it triggers on click. manually calling it didn't seem to work on the success event, but figured this is fine.
* list-items show as display:block on desktop, and kept the position:absolute

**Comment by aleesteele** [comment]
The `social` include has been deleted & the line changed to 1px. 

Going to double check with Tucker about the styles (in terms of color & alignment), because I think she said she preferred both to be blue with an orange hover.

**Pull request merged**
